[build-system]
requires = [
    "setuptools>=42",
    "wheel",
    "pybind11>=2.8.0",
]

build-backend = "setuptools.build_meta"

[tool.cibuildwheel]
test-command = "python {project}/test/test_systematics.py"

[[tool.cibuildwheel.overrides]]
select = "*-musllinux_x86_64"
before-all = "rm setup.py && mv setup_old_cpp.py setup.py"