[build-system]
requires = [
    "setuptools>=42",
    "wheel",
    "pybind11>=2.8.0",
]

build-backend = "setuptools.build_meta"

[tool.cibuildwheel]
test-command = "python {project}/test/test_systematics.py"
skip = "*musllinux*"
test-requires = "pytest"
before-test = "cp {project}/test/assets/* ."